ITI Project/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ITI_Project.Models
{
    public class Category
    {
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        [DisplayName("Category Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required!")]
        [DisplayName("Category Description")]
        public string Description { get; set; }

        public virtual ICollection<Product> Products { get; set; } = new HashSet<Product>();
    }
}

ITI Project/Controllers/CategoryController.cs
using ITI_Project.Context;
using ITI_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ITI_Project.Controllers
{
    public class CategoryController : Controller
    {
        MarketContext marketContext = new MarketContext();

        [HttpGet]
        public IActionResult Index()
        {
            var categories = marketContext.Categories;
            return View(categories);
        }

        [HttpGet]
        public IActionResult ViewDetails(int id)
        {
            var category = marketContext.Categories
                                        .FirstOrDefault(c => c.CategoryId == id);
            return View(category);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "All Fields Are Reqired");
                return View();
            }
            marketContext.Categories.Update(category);
            marketContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var category = marketContext.Categories
                                        .FirstOrDefault(c => c.CategoryId == id);
            if (category == null)
            {
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "All Fields Are Reqired");
                return View();
            }
            marketContext.Categories.Update(category);
            marketContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var category = marketContext.Categories
                                        .FirstOrDefault(c => c.CategoryId == id);
            if (category == null)
            {
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var category = marketContext.Categories.Find(id);
            if (category != null)
            {
                marketContext.Categories.Remove(category);
                marketContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ITI Project/Views/Category/Create.cshtml
@model Category

<h2>Create Category</h2>

<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group mt-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="my-4">
        <input type="submit" name="name" value="Add Category" class="btn btn-success mx-2" />
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary mx-2">Back</a>
    </div>
</form>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ITI Project/Views/Category/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Category

@{
}

<h1 style="color:red">Are You Sure You Want To Delete This Category</h1>
<br />
<h2 style="color:red">This Will Delete All Products In This Category</h2>

<table class="table text-center">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Catergory Id</th>
            <th scope="col">@Model.CategoryId</th>
        </tr>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">@Model.Name</th>
        </tr>
    </tbody>
</table>
<form asp-controller="Category" asp-action="Remove" asp-route-id="@Model.CategoryId" method="post" class="d-inline">
    <button type="submit" class="btn btn-danger mx-2">Delete</button>
</form>
<a asp-controller="Category" asp-action="Index" asp-route-id="@Model.CategoryId" class="btn btn-secondary mx-2">Back</a>

ITI Project/Views/Category/Edit.cshtml
@model Category

<h2>Edit Category</h2>

<form asp-action="Edit">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="CategoryId" />

    <div class="form-group mt-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" value="@Model.Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control" value="@Model.Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="my-4">
        <input type="submit" name="name" value="Edit Category" class="btn btn-warning mx-2" />
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary mx-2">Back</a>
    </div>
</form>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ITI Project/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<Category>

@{
}
<a asp-controller="Category" asp-action="Create" class="btn btn-success m-3">Add Category</a>
<h1>Categories List</h1>
<table class="table text-center">
    <thead>
        <tr>
            <th scope="col">Category Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="col">@item.CategoryId</th>
                <th scope="col">@item.Name</th>
                <th scope="col">@item.Description</th>
                <th scope="col">
                    <a asp-controller="Category" asp-action="ViewDetails" asp-route-id="@item.CategoryId" class="btn btn-primary mx-2">View</a>
                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@item.CategoryId" class="btn btn-warning mx-2">Edit</a>
                    <a asp-controller="Category" asp-action="Delete" asp-route-id="@item.CategoryId" class="btn btn-danger mx-2">Delete</a>
                </th>
            </tr>
        }
    </tbody>
</table>

ITI Project/Views/Category/ViewDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Category

@{
}

<h1>Product Details</h1>
<table class="table text-center">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Category Id</th>
            <th scope="col">@Model.CategoryId</th>
        </tr>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">@Model.Name</th>
        </tr>
        <tr>
            <th scope="col">Description</th>
            <th scope="col">@Model.Description</th>
        </tr>
    </tbody>
</table>
<a asp-controller="Category" asp-action="Index" asp-route-id="@Model.CategoryId" class="btn btn-secondary mx-2">Back</a>