ITI Project/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ITI_Project.Models
{
    public class Product
    { 
        public int ProductId { get; set; }
        
        [Required(ErrorMessage = "Title is required!")]
        [DisplayName("Product title")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Price is required!")]
        [DisplayName("Product price")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Description is required!")]
        [DisplayName("Product description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Quantity is required!")]
        [DisplayName("Product quantity")]
        public int Quantity { get; set; }

        public string? ImagePath { get; set; }

        public int CategoryId {  get; set; }

        public virtual Category Category { get; set; }
    }
}

ITI Project/Controllers/ProductController.cs
using ITI_Project.Context;
using ITI_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ITI_Project.Controllers
{
    public class ProductController : Controller
    {
        MarketContext marketContext = new MarketContext();

        [HttpGet]
        public IActionResult Index()
        {
            var products = marketContext.Products.Include(p => p.Category);
            return View(products);
        }

        [HttpGet]
        public IActionResult ViewDetails(int id)
        {
            var product = marketContext.Products
                                       .Include(p => p.Category)
                                       .FirstOrDefault(p => p.ProductId == id);
            return View(product);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(marketContext.Categories, "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            ModelState.Remove("Category");
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "All Fields Are Reqired");
                ViewBag.Categories = new SelectList(marketContext.Categories, "CategoryId", "Name");
                return View();
            }
            marketContext.Products.Add(product);
            marketContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var product = marketContext.Products
                                      .Include(p => p.Category)
                                      .FirstOrDefault(p => p.ProductId == id);
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Categories = new SelectList(marketContext.Categories, "CategoryId", "Name");
            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            ModelState.Remove("Category");
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "All Fields Are Reqired");
                ViewBag.Categories = new SelectList(marketContext.Categories, "CategoryId", "Name");
                return View();
            }
            marketContext.Products.Update(product);
            marketContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = marketContext.Products
                                       .FirstOrDefault(p => p.ProductId == id);
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            var product = marketContext.Products.Find(id);
            if (product != null)
            {
                marketContext.Products.Remove(product);
                marketContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ITI Project/Views/Product/Create.cshtml
@model Product

@{
    var categories = ViewBag.Categories;
}

<h2>Add Product</h2>

<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>


    <div class="form-group mt-3">
        <label asp-for="Title" class="form-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Price" class="form-label"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Quantity" class="form-label"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="ImagePath" class="form-label"></label>
        <input asp-for="ImagePath" class="form-control" />
    </div>

    <div class="form-group mt-3">
        <label asp-for="Category" class="form-label"></label>
        <select asp-items="ViewBag.Categories" asp-for="CategoryId" class="form-control"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <div class="my-4">
        <input type="submit" name="name" value="Add Product" class="btn btn-success mx-2" />
        <a asp-controller="Product" asp-action="Index" class="btn btn-secondary mx-2">Back</a>
    </div>
</form>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ITI Project/Views/Product/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Product

@{
}

<h1 style="color:red">Are You Sure You Want To Delete This Product</h1>
<table class="table text-center">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Product Id</th>
            <th scope="col">@Model.ProductId</th>
        </tr>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">@Model.Title</th>
        </tr>
    </tbody>
</table>
<form asp-controller="Product" asp-action="Remove" asp-route-id="@Model.ProductId" method="post" class="d-inline">
    <button type="submit" class="btn btn-danger mx-2">Delete</button>
</form>
<a asp-controller="Product" asp-action="Index" class="btn btn-secondary mx-2">Back</a>

ITI Project/Views/Product/Edit.cshtml
@model Product

@{
    var categories = ViewBag.Categories;
}

<h2>Edit Product</h2>

<form asp-action="Edit">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="ProductId" />

    <div class="form-group mt-3">
        <label asp-for="Title" class="form-label"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Price" class="form-label"></label>
        <input asp-for="Price" class="form-control" value="@Model.Price" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Description" class="form-label"></label>
        <input asp-for="Description" class="form-control" value="@Model.Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="Quantity" class="form-label"></label>
        <input asp-for="Quantity" class="form-control" value="@Model.Quantity" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <label asp-for="ImagePath" class="form-label"></label>
        <input asp-for="ImagePath" class="form-control" value="@Model.ImagePath" />
    </div>

    <div class="form-group mt-3">
        <label asp-for="Category" class="form-label"></label>
        <select asp-items="ViewBag.Categories" asp-for="CategoryId" class="form-control"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <div class="my-4">
        <input type="submit" name="name" value="Edit Product" class="btn btn-warning mx-2" />
        <a asp-controller="Product" asp-action="Index" class="btn btn-secondary mx-2">Back</a>
    </div>
</form>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ITI Project/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<Product>

@{
}
<a asp-controller="Category" asp-action="Index" class="btn btn-success m-3">Go To Categories</a>
<a asp-controller="Product" asp-action="Create" class="btn btn-success m-3">Add Product</a>
    <h1>Products List</h1>
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">Product Id</th>
                <th scope="col">Title</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
                <th scope="col">Quantity</th>
                <th scope="col">Image</th>
                <th scope="col">Category Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="col">@item.ProductId</th>
                    <th scope="col">@item.Title</th>
                    <th scope="col">@item.Price</th>
                    <th scope="col">@item.Description</th>
                    <th scope="col">@item.Quantity</th>
                    <th scope="col"><img src=@item.ImagePath alt="No Image Found"></th>
                    <th scope="col">@item.Category.Name</th>
                    <th scope="col">
                        <a asp-controller="Product" asp-action="ViewDetails" asp-route-id="@item.ProductId" class="btn btn-primary mx-2">View</a>
                        <a asp-controller="Product" asp-action="Edit" asp-route-id="@item.ProductId" class="btn btn-warning mx-2">Edit</a>
                        <a asp-controller="Product" asp-action="Delete" asp-route-id="@item.ProductId" class="btn btn-danger mx-2">Delete</a>
                    </th>
                </tr>
            }
        </tbody>
    </table>

ITI Project/Views/Product/ViewDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Product

@{
}

<h1>Product Details</h1>
<table class="table text-center">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="col">Product Id</th>
            <th scope="col">@Model.ProductId</th>  
        </tr>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">@Model.Title</th>
        </tr>
        <tr>
            <th scope="col">Price</th>
            <th scope="col">@Model.Price</th>
        </tr>
        <tr>
            <th scope="col">Description</th>
            <th scope="col">@Model.Description</th>
        </tr>
        <tr>
            <th scope="col">Quantity</th>
            <th scope="col">@Model.Quantity</th>
        </tr>
        <tr>
            <th scope="col">Category Name</th>
            <th scope="col">@Model.Category.Name</th>
        </tr>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col"><img src=@Model.ImagePath alt="No Image Found"></th>
        </tr>
    </tbody>
</table>
 <a asp-controller="Product" asp-action="Index" asp-route-id="@Model.ProductId" class="btn btn-secondary mx-2">Back</a>